<a href="https://colab.research.google.com/github/solobala/ABD26/blob/main/MDS27_DZ2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Домашнее задание "Линейная алгебра. Матрицы".
Уровень 0:
Задание 1
Создайте матрицу 3 на 3, заполненную числами от 1 до 9

Прибавьте к ней матрицу с единицами на диагонали

Умножьте полученную матрицу на вектор (1, 2, 3)

Вычислить транспонированную матрицу 
 от полученной в результате прибавления матрицы

Посчитайте обратную матрицу к полученной в результате прибавления матрице

In [2]:
import numpy as np
A1 = np.array([[1,2,3], [4,5,6], [7,8,9]]) #  Создайте матрицу 3 на 3, заполненную числами от 1 до 9
A1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
A2 = np.eye(3)
A2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
A3 = A1 + A2 #  Прибавьте к ней матрицу с единицами на диагонале
A3

array([[ 2.,  2.,  3.],
       [ 4.,  6.,  6.],
       [ 7.,  8., 10.]])

In [ ]:
B = np.array([1,2,3])
A4 = np.matmul(A3, B) #  Умножьте полученную матрицу на вектор (1, 2, 3)
A4

array([15., 34., 53.])

In [ ]:
A5 = np.transpose(A3) #  Вычислить транспонированную матрицу от полученной в результате прибавления матрицы
A5

array([[ 2.,  4.,  7.],
       [ 2.,  6.,  8.],
       [ 3.,  6., 10.]])

In [ ]:
A6 = np.linalg.inv(A3) #  Посчитайте обратную матрицу к полученной в результате прибавления матрице
A6

array([[-6.00000000e+00, -2.00000000e+00,  3.00000000e+00],
       [-1.00000000e+00,  5.00000000e-01, -2.33146835e-16],
       [ 5.00000000e+00,  1.00000000e+00, -2.00000000e+00]])

In [ ]:
A3 @ A6 # проверка правильности нахождения обратной матрицы. Произведение 2 матриц - единичная матрица

array([[ 1.00000000e+00, -3.33066907e-16,  6.66133815e-16],
       [-5.32907052e-15,  1.00000000e+00,  1.33226763e-15],
       [-1.77635684e-15, -1.11022302e-15,  1.00000000e+00]])

In [ ]:
np.linalg.det(A3) * np.linalg.det(A6) # проверка правильности нахождения обратной матрицы. Произведение определителей 2 матриц - единица

0.9999999999999988

#### Уровень 1:
Задание 2
Найдите собственные значения и собственные вектора матрицы:

m = np.array([[2, 2],
              [1, 3]])
print(m)

In [ ]:
m = np.array([[2, 2], [1, 3]])
res = np.linalg.eig(m)  #  Найдите собственные значения и собственные вектора матрицы
res

(array([1., 4.]), array([[-0.89442719, -0.70710678],
        [ 0.4472136 , -0.70710678]]))

#### Приведем собственные вектора в более красивый вид. Для этого транспонируем матрицу с векторами и выполним нормирование каждого из векторов

In [ ]:
res2 = res[1]
res3 = np.transpose(res2)
res3

array([[-0.89442719,  0.4472136 ],
       [-0.70710678, -0.70710678]])

In [ ]:
res3[0]/0.4472136

array([-1.99999998,  0.99999999])

In [ ]:
res3[1]/0.70710678

array([-1., -1.])

#### Задание 3
Придумайте матрицу, у которой определитель = 1, и все элементы не равны 0.

P.S. Матрица должна быть ненулевой и размерностью не менее 2!

In [ ]:
A1 = np.array([[4,7], [1,2]])
np.linalg.det(A1)

1.0

In [ ]:
A2=np.array([[1,1,2],[3,1,1],[2,1,1]])
np.linalg.det(A2)

1.0000000000000002

Просто подобрала. Алгоритм решения задачи для матрицы произвольного размера не придумала.

In [ ]:
det = 0

while det != 1:
    a = np.random.randint(-10,10,(5,5))
    det=np.linalg.det(a)
    
print('искомая матрица: \n',a)